// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: api/validator_v1/validator.proto

package validator_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_api_validator_v1_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_validator_v1_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_api_validator_v1_validator_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCorrect     bool                   `protobuf:"varint,1,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_api_validator_v1_validator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_validator_v1_validator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_api_validator_v1_validator_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *ValidateResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_api_validator_v1_validator_proto protoreflect.FileDescriptor

const file_api_validator_v1_validator_proto_rawDesc = "" +
	"\n" +
	" api/validator_v1/validator.proto\x12\tvalidator\"'\n" +
	"\x0fValidateRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"I\n" +
	"\x10ValidateResponse\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x01 \x01(\bR\tisCorrect\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer2X\n" +
	"\x0fEmailValidation\x12E\n" +
	"\bValidate\x12\x1a.validator.ValidateRequest\x1a\x1b.validator.ValidateResponse\"\x00B7Z5github.com/vvvvgross/email-validator/api/validator_v1b\x06proto3"

var (
	file_api_validator_v1_validator_proto_rawDescOnce sync.Once
	file_api_validator_v1_validator_proto_rawDescData []byte
)

func file_api_validator_v1_validator_proto_rawDescGZIP() []byte {
	file_api_validator_v1_validator_proto_rawDescOnce.Do(func() {
		file_api_validator_v1_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_validator_v1_validator_proto_rawDesc), len(file_api_validator_v1_validator_proto_rawDesc)))
	})
	return file_api_validator_v1_validator_proto_rawDescData
}

var file_api_validator_v1_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_validator_v1_validator_proto_goTypes = []any{
	(*ValidateRequest)(nil),  // 0: validator.ValidateRequest
	(*ValidateResponse)(nil), // 1: validator.ValidateResponse
}
var file_api_validator_v1_validator_proto_depIdxs = []int32{
	0, // 0: validator.EmailValidation.Validate:input_type -> validator.ValidateRequest
	1, // 1: validator.EmailValidation.Validate:output_type -> validator.ValidateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_validator_v1_validator_proto_init() }
func file_api_validator_v1_validator_proto_init() {
	if File_api_validator_v1_validator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_validator_v1_validator_proto_rawDesc), len(file_api_validator_v1_validator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_validator_v1_validator_proto_goTypes,
		DependencyIndexes: file_api_validator_v1_validator_proto_depIdxs,
		MessageInfos:      file_api_validator_v1_validator_proto_msgTypes,
	}.Build()
	File_api_validator_v1_validator_proto = out.File
	file_api_validator_v1_validator_proto_goTypes = nil
	file_api_validator_v1_validator_proto_depIdxs = nil
}
